### PR TITLE
question words: Add "Is"

### PR DESCRIPTION
**Pull request by juharris**
Depends on #1

### CODE REVIEW

**Comment by PrekshaNema25** [comment]
Is should not be added in question words.

**Comment by juharris** [comment]
Is "Is" not a valid way to ask a question? 😉 Is there any more information that you can provide on why "Is" should not be in the question words?  Is it a good idea to add a comment above `question_words_global` about why "Is" should not be in it?

**Comment by juharris** [comment]
There are a few other words that I might want to add like: "Can", "Do", "Does", etc.

**Comment by PrekshaNema25** [comment]
So Is, Can, Do, Does are not a part of 7-question words ( Wh-questions and How), and these words could be a part of stopwords as well, instead of just being a question word. The importance of such words "is" currently being handled in general as a part of stop words :-) . Secondly, if you feel that your dataset contains such kind of questions, feel free to add them in question_words_global, but generally they should not be a part of it.

**Comment by juharris** [comment]
Makes sense. I thought it would be something about stop words.  Indeed I might add them for my use case. Thanks for the explanation!

**Pull request closed without merging**
